small date fix in changelog from commit 0a06735a4d
added OAuth2 support

version not available for read-only spreadsheets

bumped version; updated changelog

Make sure the response from the DELETE request when deleting a worksheet gets read by the client else we get a httplib.ResponseNotReady error on the next request to that HTTP connection.  Also added a test and a couple of entries in the test config.  Fixes #84.

Adding an insert_row function

pep8fied

Automatically refresh OAuth2 token when it has expired.

Update README.md

Adding row selection for keys in method get_all_records.
Adding the correspoding test case.

added worksheet export #12

Add title proeprty on Spreadsheet

Along the way, the `id` property was changed to be calculated
on the fly from the feed entry which is now stored on the Spreadsheet.

Added the `numeric_value` attribute to `Cell`

This is useful in cases where the cell's text value has been formatted
with less precision than what is actually available.
It might also help to detect cells whose values have been formatted as
date or date time.

What to do when you get 403 errors

Rearranged sections, fixed capitalization

Referenced Two Factor Authorization section

Clarified what goes into the OAuth2Credentials object

The documentation for `oauth2client` is piss-poor, so I worked through [one of their examples](https://github.com/google/oauth2client/blob/master/samples/oauth2_for_devices.py) to make a valid credentials object. Because there are other libraries that speak OAuth 2.0 and feature better documentation than `oauth2client`, this change might make it easier for people to use `gspread`.

Moved docs to Read The Docs

bumped version; updated changelog #197 #183

Link to readthedocs

Removed obsolete scope url #217 #218

Added some instructions on how to get credentials

output error response #219 #170 #194

bumped version

added deprecation warning #210

Deprecation warning #210

fixed deprecation warning; fixed missing attribute #220 #187

bumped version; updated history

Emphasized the final step of oAuth2 credentials set up #226

Typo fix

Found a typo in docs and figured I would fix it.

Update client.py

added workaround for python3 users

Update README.md

Corrected the wording #234

Troubleshooting No crypto library available exception.

Not relevant any longer due to removal of the ClientLogin

Added requirements to the instruction #236

Squashing all the commits to simpy things for merge

I have insert_column.py

Update models.py

Update models.py

enumerates should be enumerate

Update models.py

'r' modified to 'col'

Update models.py

changing co-ordiniates from [col, c] to [c,col]

Update models.py

newcell = self #chaging the coordinates

Update models.py

newcell = self.cell(col, c + (index - 1))

Update models.py

newcell = self.cell(c, col + (index - 1))

Update models.py

newcell.value = columns_after_insert[c - 1][col - 1]

Update models.py

newcell.value = columns_after_insert[col - 1][c - 1]

Update models.py

newcell.value = columns_after_insert[c - 1][col - 1]

Update models.py

column to col

Update models.py

c1 + (index - 1)

Update models.py

Update models.py

Update models.py

Update models.py

Update models.py

Update models.py

Update models.py

Update models.py

Update models.py

Update models.py

Update models.py

Update models.py

Update models.py

First and best attempt!!

Update models.py

Best Update 2

Update models.py

for items in all_cells:
            columns_after_insert.append(item[1:])
newcell = self.cell(col + (index - 1), c)

Update models.py

Final Move!!

Update models.py

if condition

Update models.py

complete fresh only if else

Update models.py

Indentation Error

Add Readmyscript.txt

remove Readmyscript.txt

gspread/models.py

tests/test.py

Update models.py

if col==1:
                for c, cell in enumerate(column, start=3):
                    newcell = self.cell(c, col + (index - 1))
                    newcell.value = columns_after_insert[col - 1][subindex - 1]
                    subindex += 1
                    new_cell_list.append(newcell)
           else:

Update models.py

Update models.py

Final modifications!!

subindex and comments removed

Most Recent 29 July 2015 Commit

I have rectified all the mistakes as pointed by @barnesh

turn on travis-ci

switched tests to oauth

Note that append_row() may be right at the bottom of a new sheet.

This helps to clarify issues like #67.

fixed export test

Fixed HTTPError usage

Fix bug:
AttributeError: 'HTTPError' object has no attribute 'read'

fix AttributeError: 'HTTPError' object has no attribute 'read'

added test for Worksheet "updated" property

use uuid for test values generation

remove print

Altered insert_row semantics to utilize range

This avoids issuing one API request per cell to retrieve the Cell
objects after the insertion row. This provides a significant speed-up
for insertions at the beginning of large sheets.

Optimized row_values and col_values

Removed the _fetch_cells call for each method. This eliminates the
adverse effect on runtime for large worksheets.

Fixes #285, #190, #179, and #113

Optimized row_values and col_values

Removed the _fetch_cells call for each method. This eliminates the
adverse effect on runtime for large worksheets.

Fixes #285, #190, #179, and #113

turn on travis-ci

switched tests to oauth

Note that append_row() may be right at the bottom of a new sheet.

This helps to clarify issues like #67.

fixed export test

Fixed HTTPError usage

Fix bug:
AttributeError: 'HTTPError' object has no attribute 'read'

fix AttributeError: 'HTTPError' object has no attribute 'read'

added test for Worksheet "updated" property

use uuid for test values generation