Revert "add: Python 3.14-alpha.4 support."
This reverts commit def749047ad0b0a836e2f3908a544e659245166a.
Because `pydantic`, one of dependencies, does not appear to support Python 3.14-alpha.4. A part of errors is following:

```
  × Building wheel for pydantic-core (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [64 lines of output]
      Running `maturin pep517 build-wheel -i /opt/hostedtoolcache/Python/3.14.0-alpha.4/x64/bin/python --compatibility off`
      📦 Including license file "/tmp/pip-install-pq_aihtj/pydantic-core_31e4be53493445af80a37195491c61b2/LICENSE"
      🍹 Building a mixed python/rust project
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.14 at /opt/hostedtoolcache/Python/3.14.0-alpha.4/x64/bin/python
      📡 Using build options features, bindings from pyproject.toml
         Compiling proc-macro2 v1.0.86
         Compiling unicode-ident v1.0.12
         Compiling target-lexicon v0.12.14
         Compiling python3-dll-a v0.2.10
         Compiling once_cell v1.19.0
         Compiling stable_deref_trait v1.2.0
         Compiling autocfg v1.3.0
         Compiling libc v0.2.155
         Compiling heck v0.5.0
         Compiling num-traits v0.2.19
         Compiling pyo3-build-config v0.22.2
         Compiling litemap v0.7.3
         Compiling version_check v0.9.5
         Compiling quote v1.0.36
         Compiling writeable v0.5.5
         Compiling syn v2.0.68
         Compiling rustversion v1.0.17
         Compiling memoffset v0.9.1
         Compiling memchr v2.7.4
         Compiling pyo3-ffi v0.22.2
         Compiling pyo3-macros-backend v0.22.2
      error: failed to run custom build command for `pyo3-ffi v0.22.2`

      Caused by:
        process didn't exit successfully: `/tmp/pip-install-pq_aihtj/pydantic-core_31e4be53493445af80a37195491c61b2/target/release/build/pyo3-ffi-cbe9fbe36179524e/build-script-build` (exit status: 1)
        --- stdout
        cargo:rustc-check-cfg=cfg(Py_LIMITED_API)
        cargo:rustc-check-cfg=cfg(PyPy)
        cargo:rustc-check-cfg=cfg(GraalPy)
        cargo:rustc-check-cfg=cfg(py_sys_config, values("Py_DEBUG", "Py_REF_DEBUG", "Py_TRACE_REFS", "COUNT_ALLOCS"))
        cargo:rustc-check-cfg=cfg(invalid_from_utf8_lint)
        cargo:rustc-check-cfg=cfg(pyo3_disable_reference_pool)
        cargo:rustc-check-cfg=cfg(pyo3_leak_on_drop_without_reference_pool)
        cargo:rustc-check-cfg=cfg(diagnostic_namespace)
        cargo:rustc-check-cfg=cfg(c_str_lit)
        cargo:rustc-check-cfg=cfg(Py_3_7)
        cargo:rustc-check-cfg=cfg(Py_3_8)
        cargo:rustc-check-cfg=cfg(Py_3_9)
        cargo:rustc-check-cfg=cfg(Py_3_10)
        cargo:rustc-check-cfg=cfg(Py_3_11)
        cargo:rustc-check-cfg=cfg(Py_3_12)
        cargo:rustc-check-cfg=cfg(Py_3_13)
        cargo:rerun-if-env-changed=PYO3_CROSS
        cargo:rerun-if-env-changed=PYO3_CROSS_LIB_DIR
        cargo:rerun-if-env-changed=PYO3_CROSS_PYTHON_VERSION
        cargo:rerun-if-env-changed=PYO3_CROSS_PYTHON_IMPLEMENTATION
        cargo:rerun-if-env-changed=PYO3_PRINT_CONFIG
        cargo:rerun-if-env-changed=PYO3_USE_ABI3_FORWARD_COMPATIBILITY

        --- stderr
        error: the configured Python interpreter version (3.14) is newer than PyO3's maximum supported version (3.13)
        = help: please check if an updated version of PyO3 is available. Current version: 0.22.2
        = help: set PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 to suppress this check and build anyway using the stable ABI
      warning: build failed, waiting for other jobs to finish...
```