# This is a combination of 2 commits. # The first commit's message is:
# This is a combination of 4 commits.
# The first commit's message is:
# This is a combination of 2 commits.
# The first commit's message is:

# This is a combination of 2 commits.
# The first commit's message is:

# This is a combination of 4 commits.
# The first commit's message is:
# This is a combination of 2 commits.
# The first commit's message is:

# This is a combination of 8 commits.
# The first commit's message is:
# This is a combination of 16 commits.
# The first commit's message is:
# This is a combination of 13 commits.
# The first commit's message is:
added shortcut command, courtesy of @kennethreitz

# This is the 2nd commit message:

fixed regression bug #130. Not every POST needs If-Match header

# This is the 3rd commit message:

bumped version

# This is the 4th commit message:

small date fix in changelog from commit 0a06735a4d

# This is the 5th commit message:

added OAuth2 support

# This is the 6th commit message:

version not available for read-only spreadsheets

# This is the 7th commit message:

bumped version; updated changelog

# This is the 8th commit message:

Make sure the response from the DELETE request when deleting a worksheet gets read by the client else we get a httplib.ResponseNotReady error on the next request to that HTTP connection.  Also added a test and a couple of entries in the test config.  Fixes #84.

# This is the 9th commit message:

Adding an insert_row function

# This is the 10th commit message:

pep8fied

# This is the 11th commit message:

Automatically refresh OAuth2 token when it has expired.

# This is the 12th commit message:

Update README.md
# This is the 13th commit message:

Adding row selection for keys in method get_all_records.
Adding the correspoding test case.

# This is the 2nd commit message:

Add title proeprty on Spreadsheet

Along the way, the `id` property was changed to be calculated
on the fly from the feed entry which is now stored on the Spreadsheet.

# This is the 3rd commit message:

Added the `numeric_value` attribute to `Cell`

This is useful in cases where the cell's text value has been formatted
with less precision than what is actually available.
It might also help to detect cells whose values have been formatted as
date or date time.
# This is the 4th commit message:

What to do when you get 403 errors
# This is the 5th commit message:

Rearranged sections, fixed capitalization
# This is the 6th commit message:

Referenced Two Factor Authorization section
# This is the 7th commit message:

Clarified what goes into the OAuth2Credentials object

The documentation for `oauth2client` is piss-poor, so I worked through [one of their examples](https://github.com/google/oauth2client/blob/master/samples/oauth2_for_devices.py) to make a valid credentials object. Because there are other libraries that speak OAuth 2.0 and feature better documentation than `oauth2client`, this change might make it easier for people to use `gspread`.
# This is the 8th commit message:

Moved docs to Read The Docs
# This is the 9th commit message:

bumped version; updated changelog #197 #183

# This is the 10th commit message:

Link to readthedocs
# This is the 11th commit message:

Removed obsolete scope url #217 #218
# This is the 12th commit message:

Added some instructions on how to get credentials
# This is the 13th commit message:

output error response #219 #170 #194

# This is the 14th commit message:

bumped version

# This is the 15th commit message:

added deprecation warning #210

# This is the 16th commit message:

Deprecation warning #210

# This is the 2nd commit message:

bumped version; updated history

# This is the 3rd commit message:

Emphasized the final step of oAuth2 credentials set up #226
# This is the 4th commit message:

Typo fix

Found a typo in docs and figured I would fix it.
# This is the 5th commit message:

Update client.py
# This is the 6th commit message:

added workaround for python3 users

# This is the 7th commit message:

Update README.md
# This is the 8th commit message:

Corrected the wording #234

# This is the 2nd commit message:

Not relevant any longer due to removal of the ClientLogin

# This is the 2nd commit message:

turn on travis-ci

# This is the 3rd commit message:

switched tests to oauth

# This is the 4th commit message:

Note that append_row() may be right at the bottom of a new sheet.

This helps to clarify issues like #67.

# This is the 2nd commit message:

Fixed HTTPError usage

# This is the 2nd commit message:

fix AttributeError: 'HTTPError' object has no attribute 'read'

# This is the 2nd commit message:

Altered insert_row semantics to utilize range

This avoids issuing one API request per cell to retrieve the Cell
objects after the insertion row. This provides a significant speed-up
for insertions at the beginning of large sheets.

# This is the 3rd commit message:

Optimized row_values and col_values

Removed the _fetch_cells call for each method. This eliminates the
adverse effect on runtime for large worksheets.

Fixes #285, #190, #179, and #113

# This is the 4th commit message:

Optimized row_values and col_values

Removed the _fetch_cells call for each method. This eliminates the
adverse effect on runtime for large worksheets.

Fixes #285, #190, #179, and #113

# This is the 2nd commit message:

small date fix in changelog from commit 0a06735a4d

added OAuth2 support

version not available for read-only spreadsheets

bumped version; updated changelog

Make sure the response from the DELETE request when deleting a worksheet gets read by the client else we get a httplib.ResponseNotReady error on the next request to that HTTP connection.  Also added a test and a couple of entries in the test config.  Fixes #84.

Adding an insert_row function

pep8fied

Automatically refresh OAuth2 token when it has expired.

Update README.md

Adding row selection for keys in method get_all_records.
Adding the correspoding test case.

added worksheet export #12

Add title proeprty on Spreadsheet

Along the way, the `id` property was changed to be calculated
on the fly from the feed entry which is now stored on the Spreadsheet.

Added the `numeric_value` attribute to `Cell`

This is useful in cases where the cell's text value has been formatted
with less precision than what is actually available.
It might also help to detect cells whose values have been formatted as
date or date time.

What to do when you get 403 errors

Rearranged sections, fixed capitalization

Referenced Two Factor Authorization section

Clarified what goes into the OAuth2Credentials object

The documentation for `oauth2client` is piss-poor, so I worked through [one of their examples](https://github.com/google/oauth2client/blob/master/samples/oauth2_for_devices.py) to make a valid credentials object. Because there are other libraries that speak OAuth 2.0 and feature better documentation than `oauth2client`, this change might make it easier for people to use `gspread`.

Moved docs to Read The Docs

bumped version; updated changelog #197 #183

Link to readthedocs

Removed obsolete scope url #217 #218

Added some instructions on how to get credentials

output error response #219 #170 #194

bumped version

added deprecation warning #210

Deprecation warning #210

fixed deprecation warning; fixed missing attribute #220 #187

bumped version; updated history

Emphasized the final step of oAuth2 credentials set up #226

Typo fix

Found a typo in docs and figured I would fix it.

Update client.py

added workaround for python3 users

Update README.md

Corrected the wording #234

Troubleshooting No crypto library available exception.

Not relevant any longer due to removal of the ClientLogin

Added requirements to the instruction #236