Update README.md
Corrected the wording #234

Troubleshooting No crypto library available exception.

Not relevant any longer due to removal of the ClientLogin

Added requirements to the instruction #236

turn on travis-ci

switched tests to oauth

Note that append_row() may be right at the bottom of a new sheet.

This helps to clarify issues like #67.

fixed export test

Fixed HTTPError usage

Fix bug:
AttributeError: 'HTTPError' object has no attribute 'read'

fix AttributeError: 'HTTPError' object has no attribute 'read'

added test for Worksheet "updated" property

use uuid for test values generation

remove print

Altered insert_row semantics to utilize range

This avoids issuing one API request per cell to retrieve the Cell
objects after the insertion row. This provides a significant speed-up
for insertions at the beginning of large sheets.

Optimized row_values and col_values

Removed the _fetch_cells call for each method. This eliminates the
adverse effect on runtime for large worksheets.

Fixes #285, #190, #179, and #113

Optimized row_values and col_values

Removed the _fetch_cells call for each method. This eliminates the
adverse effect on runtime for large worksheets.

Fixes #285, #190, #179, and #113

Added __iter__ method to Spreadsheet class

Added test_worksheet_iteration to SpreadsheetTest

Fixed failing tests, refactored WorksheetTests

Fixed AttributeError when URLError caught by HTTPError catch block

Fixes #257

Fixed utf8 encoding error caused by duplicate XML declarations

Basically, the implementation of update_cells modified the XML response of an
API query and then called _add_xml_header on _that_. This resulted in two XML
declarations being sent with the response.

For reasons I don't care to explore further, these two declarations caused the
Google API to strip unicode code points from the request. The net effect was
that update_cell processed unicode code points fine and update_cells didn't.

Fixes #106 where this defect was reported.

Fix broken image

Remove an obsolete reference and the old logo

Adjusted test for i18n

Add CellNotFound to module exports

Fixes #88

DOC: documentation about encoding private_key

Directly call `encode` on the `str` rather than implicitly through bytes.

DOC: legacy python -> python2

Use Python requests instead of the native HTTPConnection object

Replace old code with 'requests' in the least intrusive way possible

Raise an exception when an unsupported HTTP method is supplied

Add requirements.txt

Minor changes

- Relocate an import statement
- Remove unused code

Remove requirements.txt

Use .text instead of .content

Added spreadsheet feed helper

Added first mock test, fixed test_utils

Fix all the tests!

-Added all supported Python versions to tox

-Change back to response.content from response.text to address Python 3
encoding issue.

-Removed Python 3.2 testing from travis because oauth2client does not support
this version.

-Fixed XML header issue with Python 3

-Fixed Worksheet.export function and associated test

Adjusted travis config to install requirements

Removed config from mock tests, removed 2.5 from travis

Fix setup import error

`import gspread` statement caused requests packaged to be imported before
dependency could be installed. Sole purpose of import was to extract the
__version__ string field on the module.

Solution is to use a regex to read the version string from __init__.py

Fixes #317

Mocked config parser to fix travis path issues

Changed re-raise semantics to preserve stack trace

Added MockSpreadsheetTest

bumped the version number; updated the changelog

remove the basic usage from the pypi page

remove a redundant GitHub link

add the How to Contribute section; link contributors to the github graphs

fix typo

Make Documentation Current

Fixes #336

update test.py to support oauth2client 2.0.0

oauth2 documentation update

FIX: OAuth2.rst now properly describes how to get set up with
oauth2client v2.0.0

correct typo

add section for oauth2client < 2.0.0 setup

doc update

ignore virtualenv

clean up

add test reqs

remove unused import

Fixed HTTPSession to use request sessions so that connection pool is not recreated upon every request to a spreadsheet.

Without this fix, you see following log message on every request to a spreadsheet:

...INFO|requests.packages.urllib3.connectionpool|connectionpool.py:756|_new_conn()|Starting new HTTPS connection (1): spreadsheets.google.com

Creationg HTTPS connections is expensive. So this fix impoves the overall performance significantly.

See issue #380.

added shortcut command, courtesy of @kennethreitz

fixed regression bug #130. Not every POST needs If-Match header

bumped version

small date fix in changelog from commit 0a06735a4d

added OAuth2 support

version not available for read-only spreadsheets

bumped version; updated changelog

Make sure the response from the DELETE request when deleting a worksheet gets read by the client else we get a httplib.ResponseNotReady error on the next request to that HTTP connection.  Also added a test and a couple of entries in the test config.  Fixes #84.

Adding an insert_row function

pep8fied

Automatically refresh OAuth2 token when it has expired.

Update README.md

Adding row selection for keys in method get_all_records.
Adding the correspoding test case.

Add title proeprty on Spreadsheet

Along the way, the `id` property was changed to be calculated
on the fly from the feed entry which is now stored on the Spreadsheet.

Added the `numeric_value` attribute to `Cell`

This is useful in cases where the cell's text value has been formatted
with less precision than what is actually available.
It might also help to detect cells whose values have been formatted as
date or date time.

What to do when you get 403 errors

Rearranged sections, fixed capitalization

Referenced Two Factor Authorization section

Clarified what goes into the OAuth2Credentials object

The documentation for `oauth2client` is piss-poor, so I worked through [one of their examples](https://github.com/google/oauth2client/blob/master/samples/oauth2_for_devices.py) to make a valid credentials object. Because there are other libraries that speak OAuth 2.0 and feature better documentation than `oauth2client`, this change might make it easier for people to use `gspread`.

Moved docs to Read The Docs

bumped version; updated changelog #197 #183

Link to readthedocs

Removed obsolete scope url #217 #218

Added some instructions on how to get credentials

output error response #219 #170 #194

bumped version

added deprecation warning #210

Deprecation warning #210

bumped version; updated history

Emphasized the final step of oAuth2 credentials set up #226

Typo fix

Found a typo in docs and figured I would fix it.

Update client.py

added workaround for python3 users

Update README.md

Corrected the wording #234

Not relevant any longer due to removal of the ClientLogin

turn on travis-ci

switched tests to oauth

Note that append_row() may be right at the bottom of a new sheet.

This helps to clarify issues like #67.

Fixed HTTPError usage

fix AttributeError: 'HTTPError' object has no attribute 'read'

Altered insert_row semantics to utilize range

This avoids issuing one API request per cell to retrieve the Cell
objects after the insertion row. This provides a significant speed-up
for insertions at the beginning of large sheets.

Optimized row_values and col_values

Removed the _fetch_cells call for each method. This eliminates the
adverse effect on runtime for large worksheets.

Fixes #285, #190, #179, and #113

Optimized row_values and col_values

Removed the _fetch_cells call for each method. This eliminates the
adverse effect on runtime for large worksheets.

Fixes #285, #190, #179, and #113

small date fix in changelog from commit 0a06735a4d

added OAuth2 support

version not available for read-only spreadsheets

bumped version; updated changelog

Make sure the response from the DELETE request when deleting a worksheet gets read by the client else we get a httplib.ResponseNotReady error on the next request to that HTTP connection.  Also added a test and a couple of entries in the test config.  Fixes #84.

Adding an insert_row function

pep8fied

Automatically refresh OAuth2 token when it has expired.

Update README.md

Adding row selection for keys in method get_all_records.
Adding the correspoding test case.

added worksheet export #12

Add title proeprty on Spreadsheet

Along the way, the `id` property was changed to be calculated
on the fly from the feed entry which is now stored on the Spreadsheet.

Added the `numeric_value` attribute to `Cell`

This is useful in cases where the cell's text value has been formatted
with less precision than what is actually available.
It might also help to detect cells whose values have been formatted as
date or date time.

What to do when you get 403 errors

Rearranged sections, fixed capitalization

Referenced Two Factor Authorization section

Clarified what goes into the OAuth2Credentials object

The documentation for `oauth2client` is piss-poor, so I worked through [one of their examples](https://github.com/google/oauth2client/blob/master/samples/oauth2_for_devices.py) to make a valid credentials object. Because there are other libraries that speak OAuth 2.0 and feature better documentation than `oauth2client`, this change might make it easier for people to use `gspread`.

Moved docs to Read The Docs

bumped version; updated changelog #197 #183

Link to readthedocs

Removed obsolete scope url #217 #218

Added some instructions on how to get credentials

output error response #219 #170 #194

bumped version

added deprecation warning #210

Deprecation warning #210

fixed deprecation warning; fixed missing attribute #220 #187

bumped version; updated history

Emphasized the final step of oAuth2 credentials set up #226

Typo fix

Found a typo in docs and figured I would fix it.

Update client.py

added workaround for python3 users

Update README.md

Corrected the wording #234

Troubleshooting No crypto library available exception.

Not relevant any longer due to removal of the ClientLogin

Added requirements to the instruction #236